### ISSUE TITLE
Updating C9-ATS2-install-alt.sh

### ISSUE THREAD

**Issue by githwxi** [Hibou57/PostiATS-Utilities#1]
The way to build atscc2js (and others) has been changed a bit. Please see the following
script:

https://github.com/ats-lang/ats-lang.github.io/blob/master/SCRIPT/C9-ATS2-install-cs320.sh

Could you update C9-ATS2-install-alt.sh accordingly?

I would really like to make this script the default for people to use to install ATS2 and various atsccomp transpiler (e.g., atscc2js).

Thanks!

**Comment by Hibou57** [comment]
I see, I though it was an issue with a Python script. I will tweak `C9-ATS2-install-alt.sh` and test it then update it.

**Comment by Hibou57** [comment]
It’s close to be OK, I’m just stuck on an issue while building `ATS-extsolve`, it fails complaining `json_ML.sats` and `json.sats` are not available for staloading. I tried multiple things, to no avail.

**Comment by githwxi** [comment]
I have just reproduced this bug. Will find a way to fix it shortly.

**Comment by githwxi** [comment]
It seems that the problem is fixed. Could you try again?

**Comment by Hibou57** [comment]
I updated the script in https://github.com/Hibou57/PostiATS-Utilities/blob/master/install-ats2-on-debian-ubuntu.sh (will redirect here from the old gist). I tested it, and seems fine now.
